modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Tamaized/MelonGolem/issues"
license="All Rights Reserved"

[[mods]]
    modId="melongolem"
    version="${version}"
    displayName="Melon Golem"
    credits=""
    authors="Tamaized"
    description='''
    Adds a Melon Golem
    '''

[[dependencies.melongolem]]
    modId="neoforge"
    type="required"
    versionRange="[20,)"
    ordering="NONE"
    side="BOTH"
